# NOMBRE DE LA APLICACIÓN
spring.application.name=mercado-pago

# SERVER
server.port=8081
server.servlet.application-display-name=Mercado Pago Microservice

# MERCADO PAGO
mercadopago.access.token=${MERCADOPAGO_ACCESS_TOKEN}
mercadopago.public.key=${MERCADOPAGO_PUBLIC_KEY}
mercadopago.client.id=${MERCADOPAGO_CLIENT_ID}

# URLs para Mercado Pago
frontend.url=http://localhost:4200

# URL PÚBLICA (ngrok) de ESTE microservicio -> usada como notification_url para que MercadoPago nos mande los webhooks
backend.url=https://chop-jersey-resubmit.ngrok-free.dev

# URL del BACKEND PRINCIPAL (sistema-apolloAngular, puerto 8080) -> usada para notificarle pagos confirmados
sistema.backend.url=http://localhost:8080

# LOGGING
logging.level.mercadopago.example=DEBUG
logging.level.com.mercadopago=DEBUG
logging.level.org.springframework.web=INFO

# ACTUATOR (para monitoreo)
management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true