spring.application.name=sistema-apollo

# RECAPTCHA
google.recaptcha.secret=${RECAPTCHA_SECRET}
google.recaptcha.site=6LcOWNQrAAAAAD_mcy9fM5j71rg4kr0p-THrhQ-L

# DATABASE
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:luren_db}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# SECURITY
spring.security.user.name=admin
spring.security.user.password=${ADMIN_PASSWORD:12345}

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ? ZONA HORARIA - FORZAR UTC-5 (PERU)
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima

# SERVER
server.port=8080
server.servlet.session.timeout=30m
server.servlet.session.cookie.max-age=-1
server.servlet.application-display-name=Sistema Apollo

# ERROR HANDLING
server.error.whitelabel.enabled=false
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never

# URLs para MercadoPago
frontend.url=${FRONTEND_URL:http://localhost:4200}
backend.url=${BACKEND_URL:https://chop-jersey-resubmit.ngrok-free.dev}

# WHATSAPP API
whatsapp.api.url=https://graph.facebook.com/v19.0
whatsapp.phone.number.id=${WHATSAPP_PHONE_ID}
whatsapp.token=${WHATSAPP_TOKEN}
whatsapp.verify.token=${WHATSAPP_VERIFY_TOKEN}

# Configuracion del Chatbot
chatbot.url=${CHATBOT_URL:http://localhost:8083}
chatbot.endpoint=/api/chatbot/message

# MERCADO PAGO
mercadopago.public.key=${MERCADOPAGO_PUBLIC_KEY}
mercadopago.access.token=${MERCADOPAGO_ACCESS_TOKEN}
mercadopago.service.url=${MERCADOPAGO_SERVICE_URL:http://mercadopago:5001}