spring.application.name=sistema-apollo

# RECAPTCHA
google.recaptcha.secret=${RECAPTCHA_SECRET}
google.recaptcha.site=6LcOWNQrAAAAAD_mcy9fM5j71rg4kr0p-THrhQ-L

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/luren_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# SECURITY
spring.security.user.name=admin
spring.security.user.password=${ADMIN_PASSWORD}

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# SERVER
server.port=8080
server.servlet.session.timeout=30m
server.servlet.session.cookie.max-age=-1
server.servlet.application-display-name=Sistema Apollo

# ERROR HANDLING
server.error.whitelabel.enabled=false
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never




# WHATSAPP API
whatsapp.api.url=https://graph.facebook.com/v19.0
whatsapp.phone.number.id=${WHATSAPP_PHONE_ID}
whatsapp.token=${WHATSAPP_TOKEN}
whatsapp.verify.token=${WHATSAPP_VERIFY_TOKEN}