spring.application.name=sistema-apollo


google.recaptcha.secret=${RECAPTCHA_SECRET}
google.recaptcha.site=6LcOWNQrAAAAAD_mcy9fM5j71rg4kr0p-THrhQ-L



spring.datasource.url=jdbc:postgresql://localhost:5432/luren_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Security User (temporal)
spring.security.user.name=admin
spring.security.user.password=${ADMIN_PASSWORD}



# JPA / Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.servlet.session.timeout=30m
server.servlet.session.cookie.max-age=-1
mercadopago.public.key=TEST-d635b7d9-c82a-44c1-b03c-923aedfd9b2c
mercadopago.access.token=TEST-6717229499215018-051914-bab667c41f6f0b8cae337ba33fe8d058-3412442987
mercadopago.client.id=3418672944
server.servlet.application-display-name=Sistema Apollo
# ERROR HANDLING - Agrega estas lneas al final
server.error.whitelabel.enabled=false
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never
whatsapp.api.url=https://graph.facebook.com/v19.0
whatsapp.phone.number.id=1115829448288012
whatsapp.token=EAAOGRNGkVr0BRj3lJPs0AYtJ7CKPHQG1mqxzHIVOGW5pC0ZByLSBy52ZBWKnLWUldetLu8Wihm9Q0M2A8pZBrRCyItgjZAEIFI1S6jWvDpZAQnGyw7ZCEiQJGa0S1iher23hG9j0a0VOyzwjO8AKPuhsmKUsE3cqXR7PCuVmPdbWi7B1969rBqVu5e8GY1tvJ9uWWjbMmR0BRLFaZCH7I2hLk1w6NeTHk63ZBzrnhdzLeE73BuLifU9r2kLpseqqfpiCUq7L7jXiC0TQi3ewMCr5ZBSOi
whatsapp.verify.token=3f9K!zPq_2026